brian-dot-com/config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  resources :posts, only: [:index, :create]
end

brian-dot-com/app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :body, :url, presence: true;
end

brian-dot-com/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    render :index
  end
end

brian-dot-com/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.sort_by { |post| post.title.scan(/\d+/)[0].to_i }
    respond_to do |format|
        format.html { render :index }
        format.json { render json: @posts }
      end
  end

  def create
    @post = Post.new(post_params)
    if @post.save!
      render json: @post
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :author, :body, :url, :date)
  end
end

brian-dot-com/app/helpers/posts_helper.rb
module PostsHelper
end

brian-dot-com/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrianDotCom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <div class="hang-up"></div>
    <div class="hang-down"></div>
    <section class="top-weird-corner"><div class="inward-curve"></div></section>
    <section class="bottom-weird-corner"><div class="inward-curve"></div></section>
    <div class="corner">
      <img src=
        "https://scontent-lax3-1.xx.fbcdn.net/hphotos-xfa1/v/t1.0-9/11822715_10103794455841903_1925710574001809883_n.jpg?oh=53fd144b2f7bfd66432297955644886d&oe=576B08CD"
        alt="brian's beautiful profile pic"
        id="profile_pic" />
    </div>
    <div class="corner-buffer"></div>
  </header>

<%= yield %>

</body>
</html>

brian-dot-com/app/views/pages/index.html.erb
<h1>Hello, welcome to my site.</h1>
<%= link_to "Posts!",  posts_url %>

brian-dot-com/app/views/posts/index.html.erb
<div id="results">

</div>